Yeet = "1234"
while Yeet != "x":

    print("")
    print("Game start")
    start = input("What do you want to to do?- Play=1, Achievements=2, Languages=3-   ")
    if start == "3":
        print("")
        print("Hahahahahaha, cute you thought you could change the language, sorry, too lazy.")
    if start == "2":
        print("")
        print("(*'s represent difficulty level of achievement.)")
        print("All Achievements-")
        print("Well that was quick- */2")
        print("No adventure for me- *")
        print("Durshcaburg- **")
        print("How rude- **")
        print("404 world not found- **")
        print("Yum- **")
        print("Anger the gods- ****")
        print("Hacker man- ******")
        print("Gameception- *******")
        print("How did we get here?- **********")
        print("Game won- **********")


    dev_secret = "989565222"
    if start == "1":
        print("")
        print("You find yourself in a forest, surrounded by dense trees and bushes.")
        print("You are in the centre of a circular plain.")
        print("You can hear some noises come from all around you. It unnerves you.")
        print("there is a separation of the trees out in front of you, leading to a dirt path, away from the sounds")
        print("out behind you you see a large mountain, and a sign pointing up saying Mount Ebott")
        C = input("What do you do?- hide=1, forward=2, backward=3, call for help=4-  ")
        if C == "4":  #------------------------------------------------------------------------------------------------
            print("")
            print("You shout towards the shuffling noise")
            print("Hoping to get rescued")
            print("A large being comes out of the forest and...")
            print("You can't look at the monster, you die")
            print("Achievement unlocked- Well that was quick.")
        if C == "1":  #-------------------------------------------------------------------------------------------------
            print("")
            print("you hide in the bushes, but the sounds of rustling seem to get closer and closer until")
            print("a gap looms in the trees, parting them. you hear some shuffling, as if a very big something is angry.")
            print("you can hear the noises go away")
            Ca = input("What do you do?- come out=1, stay in=2-   ")
            if Ca == "2":
                print("")
                print("You are too terrified to move, so you stay inside the bush")
                print("About 10 minutes later you feel something slide up your leg")
                print("you look down and scream just as as a small black snake bites into your leg.")
                print("You fall over and feel a tingling feeling travel up your leg, your mouth starts to foam and-")
                print("You die")
            if Ca == "1":#-----------------------------------------------------------
                print("")
                print("You muster up your courage and get out of the bush. the rustling noises have stopped,")
                print("The two other paths you saw have closed up, too overgrown to go through, but now there is a third path.")
                print("torn apart by the ravaging beast.")
                Caa = input("What do you do now?- stay still=1, beast path=2-   ")
                if Caa == "1":
                    print("")
                    print("You don't feel like going towards that beast, but the other options have closed up.")
                    print("So you stay in the circle and sit down.")
                    print("...")
                    print("...")
                    print("...")
                    print("You are boooooored")
                    print("You die")
                    Caaa = input("-   ")
                    if Caaa == "1":
                        print("")
                        print("A voice descends out of the heavens and shouts at you,")
                        print("'How did you do that? i didn't give you a prompt!!! I said you died! that means you died!'")
                        print("'I am a force to be reckoned with! Don't trifle with me young human!'")
                        print("'You are merely a tribute! You must die to the beast!'")
                        Caaaa = input("What do you respond with?-   ")
                        if Caaaa == "1":
                            print("")
                            print("You Just sit there")
                            print("'Why are you doing that??? I am an all powerful being! You don't fear me?'")
                            Caaaaa = input("What do you do?-   ")
                            if Caaaa == "1":
                                print("")
                                print("You shake your head as a no.")
                                print("'Why not??? I am an all powerful being that can do whatever I want to you!'")
                                Caaaaaa = input("What do you do?-   ")
                                if Caaaaaa == "1":
                                    print("")
                                    print("You shrug")
                                    print("You hear some screaming from the heavens and a large bolt of lightning comes do-")
                                    print("You died, for real this time")
                                    print("Achievement unlocked- Anger the Gods")
                if Caa == "2":
                    print("")
                    print("You move slowly up the broken path, jumping over fallen trees and over dead animals,")
                    print("Everything seems to be crushed, whole trees that have lived for centuries torn down.")
                    print("20 MINUTES LATER")
                    print("Eventually you see a small opening to a cliff side, not doing the immense beasts power justice")
                    Caab = input("What do you do?- go in=1, hide outside=2, fly over the cliff=3-   ")
                    if Caab == "3":
                        print("")
                        print("Up up down down left right left right B A start.")
                        print("You jump up and fly up and above the cliff")
                        print("Admin has swung the ban hammer")
                        print("You died, flying is not allowed on this server.")
                        print("For an appeal Visit thisworldthesedays.com/ban-appeal-for-pyventure.html")
                    if Caab == "1":
                        print("")
                        print("You build up your courage and tip toe into the cave.")
                        print("You look around but only find two doors, you take another step and a *snap* emits from your foot.")
                        print("You stepped on a twig.")
                        print("You look towards the doors and they burst open and you look at the-")
                        print("You die, you cannot look at the beast.")
                    elif Caab == "2":
                        print("")
                        print("Because you don't want to face the immense beast's power, you hide out in a nearby bush,")
                        print("Waiting for something to happen.")
                        print("...")
                        print("...")
                        print("40 MINUTES LATER")
                        print("You are starting to get hungry and sleepy")
                        print("But then you hear a loud bong emanate from the forest")
                        print("Suddenly the beast bolts out of the Cave.")
                        print("You duck your head down as it starts to come up to your vision")
                        print("You hear the beast barrel through the now grown over forest, freeing you up to explore.")
                        Caabb = input("What do you do?- Go in the Cave=1, Go back into the bush=2-   ")
                        if Caabb == "1":
                            print("")
                            print("You suck in a deep breath and put your big boy pants on as you walk towards the cave")
                            print("as you enter it you see the cave widen up, getting smoother until it shines, like marble.")
                            print("Finally the cave slopes up until it look like a house, light emenating from a chandelier")
                            print("You look down the quite lovely corridoor, and you see two large doors, right and left.")
                            Caabba = input("What do you do?- Right=1, Left=2-   ")
                            if Caabba == "2":
                                print("")
                                print("You walk into the left door, shoving the immense door aside.")
                                print("You walk into a large kitchen, opening up to you to explore,")
                                print("You take a step forward and look around. There are loads of spices an dirty dishes and food.")
                                print("There is a pie and a bowl of cereal.")
                                Caabbab = input("What do you eat?- Pie=1, Cereal=2-   ")
                                if Caabbab == "1":
                                    print("You take a knife and you slice into the pie.")
                                    print("You bring a plate over and lift up a piece of the pie")
                                    print("You get a fork and take a big bite of the pie.")
                                    print("Ewwwwwwwwwwwww")
                                    print("It tastes like you have bitten into sulphur inside some porceline.")
                                    print("You look down and it seems as if you have just bitten into a big white egg, too big to be a duck.")
                                    print("You hear a gasp in a very snake manner between your legs.")
                                    print("The snake looks horrifies at you")
                                    print("you look at it")
                                    print("you look at the pie")
                                    print("you look at the snake")
                                    print("you look at the egg")
                                    print("you finally connect the dots")
                                    print("The snake eats you and you die. That sucks")
                                if Caabbab == "2":
                                    print("You take the bowl f cereal and pour some milk n it from the fridge")
                                    print("You eat it")
                                    print("yum")
                                    print("Achievement unlocked- Yum")
                            if Caabba == "1":
                                print("")
                                print("You go  to the right door, pushing the giant door with all your might")
                                print("Eventually you manage to creak it open enough to walk in, you see a large room,")
                                print("You realise it is a large library, going up even further up than the corridor,")
                                print("The bookshelves going far up, up to about 4 stories up. There is also a giant chair.")
                                print("You see one book on the bottom most shelf that attracts your attention,")
                                print("You see an apple lying next to the chair on a large table. It has a bite in it.")
                                Caabbaa = input("What do you do?- Eat apple=1, Read book=2,search around=3-   ")
                                if Caabbaa == "1":
                                    print("")
                                    print("You ate the apple...")
                                    print("")
                                    print("Dev apple eaten.")
                                    print("")
                                    print("Enter developer access password.")
                                    print("")
                                    Caabbaas = input("")
                                    if Caabbaas == dev_secret:
                                        print("")
                                        print("Achievement unlocked- How did we get here?")
                                    if Caabbaas == "applequest":
                                        print("")
                                        print("Entered developer access")
                                        Caabbaass = input("What do you press?- Game files = 1,Game options = 2-   ")
                                        if Caabbaass == "1":
                                            print("")
                                            print("You enter the game files ")
                                            Caabbaassa = input("what do you do?- Delete=1, Code=2, Rename=3-   ")
                                            if Caabbaassa == "3":
                                                print("")
                                                print("You right click the file and click rename.")
                                                print("You type Butt. Haha funny")
                                                print("You died because your humor is broken.")
                                            if Caabbaassa == "1":
                                                print("")
                                                print("You go up to the game files and right click")
                                                print("You press delete")
                                                print("{ERROR 404>>>FILE NOT FOUND<>INITIATE SELF DESTRUCT}")
                                                print("{ERROR<>DEATH MESSAGE NOT FOUND>>>REBOOTING}")
                                            if Caabbaassa == "2":
                                                print("")
                                                print("You don't really know what to do, so you decide to start coding extra things.")
                                                print("3 HOURS LATER...")
                                                print("You sigh as you finish up your codathon, at the top bar you press the green triangle")
                                                Secret_ending = input("What do you want to to do?- Play=1, Achievements=2, Languages=3-   ")
                                                if Secret_ending == "3":
                                                    print("")
                                                    print("Hahahahahaha, cute you thought you could change the language, sorry, too lazy.")
                                                if Secret_ending == "2":#-----------------------------------------------------------------------------------------------------------------------------------------------
                                                    print("")
                                                    print("(*'s represent difficulty level of achievement.)")
                                                    print("All Achievements-")
                                                    print("Error 404 world not found- *")
                                                    print("Anger the god's- ***")
                                                    print("Dinosaurs!- ****")
                                                    print("Hacker man- ****")
                                                    print("How did we get here?- *****")
                                                    print("3(222)")
                                                if Secret_ending == "1":
                                                    print("")
                                                    print("You find yourself in a forest, surrounded by dense trees and bushes.")
                                                    print("You are in the centre of a circular plain.")
                                                    print("You can hear some noises come from all around you. It unnerves you.")
                                                    print("there is a separation of the trees out in front of you, leading to a dirt path, away from the sounds")
                                                    print("out behind you you see a large mountain, and a sign pointing up saying Mount Ebott")
                                                    print("And then suddenly a T-Rex comes out of the bushes and eats you")
                                                    print("Mods be crazy huh?")
                                                    print("You died because you didn't mod in invincibility.")
                                                    print("Achievement unlocked- Gameception")
                                        if Caabbaass == "2":
                                            print("")
                                            print("You enter the Game options, what do you press?")
                                            Caabbaassb = input("Language=1, Choice tree code=2, $&@^%@#)=3-   ")
                                            if Caabbaassb == "1":
                                                print("")
                                                print("you press language, and suddenly all of the characters turn to spanish")
                                                print("you cannot continue modifying the game when everything is spanish.")
                                                print("Oof, Game over.")
                                            if Caabbaassb == "2":
                                                print("")
                                                print("You go into the games choice tree,")
                                                print("You see hundreds of red lines representng deaths,")
                                                print("And white lines in the middle of them")
                                                print("On the edges of the screen you see several green dots,")
                                                print("You move your cursor over to them and click the green dot")
                                                print("Congratulations! ")
                                                print("Achievement unlocked- Hacker man")
                                    else:
                                        print("")
                                        print("Access denied, lockdown sequence initiated.")
                                        print("You die because someone is hiding something.")
                                if Caabbaa =="2":
                                    print("")
                                    print("You pick up the book, you feel its coarse leather outside with iron studdings,")
                                    print("You open it up, and just then you realise, you don't know how to read.")
                                    print("You die from cringe.")
                                if Caabbaa == "3":
                                    print("")
                                    print("You look around")
                                    print("You cant see anything except for the bookshelves and the chair")
                                    Caabbaac = input("What do you do(Pull all the books off=1, investigate the chair=2)?")
                                    if Caabbaac == "1":
                                        print("")
                                        print("You start to pull off the books")
                                        print("You look up and you see one book that catches your eye, slightly misaligned from the others,")
                                        print("You think to yourself \"That must be a secret passage book opener!\"")
                                        print("You climb up to it, about 2 stories.")
                                        print("You pull on it, and it comes off from the bookshelf.")
                                        print("You splat to the ground, maybe it really is just a library.")
                                    if Caabbaac == "2":
                                        print("")
                                        print("You go up to the giant chair, the wideness of a sofa and the height of a bunk bed")
                                        print("you look behind it, and you see a door, huh that was easy.")
                                        print("you walk up to the door, push it out of the way and come to a bedroom.")
                                        print("You see a desk, a book lying on the floor and a bed,")
                                        Caabbaacb = input("what do you do?- Sleep=1, Read=2, desk=3")
                                        if Caabbaacb == "2":
                                            print("")
                                            print("You pick up the book on the floor, it is dark and gives off a mysterious aura")
                                            print("You open it up and you realise that you still can't read.")
                                            print("You die from the cringe.")
                                        if Caabbaacb == "3":
                                            print("")
                                            print("You walk up to the fairly normal sized desk")
                                            print("You see a closed notebook, which you are uninterested in.")
                                            print("You open the desks drawers, looking in.")
                                            print("Suddenly a small black snake jumps out from the desk, biting your face,")
                                            print("You scream as you feel a tingling feeling seep into your face.")
                                            print("You die")
                                        if Caabbaacb == "1":
                                            print("")
                                            print("You lay down in the bed.")
                                            print("slowly you close your eyes and drift off to an eternal slumber.")
                                            print("You win! Congrats! You can try and explore other victories or hunt achievements!")

        if C == "2":  #-------------------------------------------------------------------------------------------------
            print("")
            print("You go off away from the scary sounds deep into the woods, adrenaline pumping through you.")
            print("you run until the circle of no trees are in the far off distance, and you can't hear the noises anymore.")
            Cb = input("What do you do?- Continue=1, Go back=2, walk off the path=3-   ")
            if Cb == "3":
                print("")
                print("You randomly walk away from the path.")
                print("You don't see much, trees, squirrels, trees, bushes, and trees.")
                print("You walk for about half a minute before-")
                print("CHOICE TREE ERROR<>FOREST NOT PROGRAMMED<>STUPIDITY OF CHAR NOT FACTORED>>>INITIATING REBOOT")
                print("Achievement unlocked- 404 world not found")
            if Cb == "2":
                print("")
                print("You decide to walk back, seeing if the scary thing has gone.")
                print("You wander back down the path, but you don't hear anything, you look around and you s-")
                print("You died, monsters can tip toe too.")
            if Cb == "1":
                print("")
                print("You decide it's best not to go back to that terrifying thing.")
                print("so you continue walking,")
                print("55 MINUTES LATER...")
                print("You come up to a large spooky mansion as a loud bong emenates from the forest.")
                print("The windows look slender slightly broken. Looking like evil eyes.")
                print("In front of you you see a porch leading to a large door, with a handle depicting a skull.")
                Cba = input("What do you do?- Stay still=1, Open door=2, Investigate=3-   ")
                if Cba == "1":
                    print("")
                    print("You pop a squat, just looking up at the house...")
                    print("Well this is boring...")
                    print("Then suddenly you feel a sharp piercing in your leg, you look down to see a small black snake biting your leg.")
                    print("You start to feel tingly all over and foam at the mouth.")
                    print("You die.")
                if Cba == "2":
                    print("")
                    print("You walk to the porch, and you turn the skull handle.")
                    print("oof, the door is locked.")
                    print("You cry")
                if Cba == "3":
                    print("You decide to walk around the house in search of... something.")
                    print("Congratulations! you found a something! three somethings in fact!")
                    print("You see a large hole in space time floating in the flower garden out back.")
                    print("You find a mysterious bump")
                    print("And you find the backdoor to the house.")
                    Cbac = input("wha do you do? - bump-1, space time hole-2, backdoor-3-   ")

        if C == "3": #--------------------------------------------------------------------------------------------------------------------------------------
            print("")
            print("You start up to head towards the large mountain looming in the distance.")
            print("Gradually as you go back you hear the sounds growing fainter and fainter.")
            print("You sigh in relief, relived that you didn't have to discover what that creature was.")
            print("You come to a crossroads, a sign pointing out in three directions.")
            print("One sign points ahead, saying 'Mt Ebbot ahead, beware' ")
            print("The sign off to your left says 'The escaped'")
            print("And the sign to your right is too worn to be read.")
            Cc = input("Where do you go?- The escaped=1 Mt Ebbot=2 right=3 back=4-   ")
            if Cc == "4":
                print("")
                print("You decide to go back, and to see where those sounds had come from.")
                print("Despite what you literally just thought like 5 seconds ago.")
                print("Why do people just insist on being stupid!! argh!")
                print("You die because an admin didn't like your choices.")
                print("Achievement unlocked- Durshcaburg")
            if Cc == "1":
                print("")
                print("")#--------------------------------------------------------------------------
            if Cc == "2":
                print("")
                print("You decide to head towards the mountain, wanting to explore.")
                print("50 MINUTES LATER...")
                print("You reach to about the base of Mt Ebbot before you hear a loud bong emmenate from far behind you.")
                print("You shrug as you continue forth, hiking up the mountain.")
                print("You are about half way up when you start to see some signs.Go back! turn away!, they say.")
                Ccb = input("What do you do?- (Go back=1, Ignore the signs=2)-   ")
                if Ccb == "2":
                    print("")
                    print("You Choose to ignore the signs and continue your hike up the mountain.")
                    print("As you reach to the top of the mountain you see that it flattens out but there is a cave.")
                    Ccbb = input("What do you do?- (Go in the cave=1, plant flag=2)")
                    if Ccbb == "1":
                        print("")
                        print("You decide to go in the cave, choosing adventure.")
                        print("You assumed it would be quite dark, but the cave has a few holes in it, allowing the sun to shine through.")
                        print("In the middle of the cave lies a hole, a fairly large one that looks too perfect to be natural.")
                        Ccbba = input("What do you do?- (Look down the hole=1, Run away=2, fart=3)-   ")
                        if Ccbba == "3":
                            print("")
                            print("how rude.")
                            print("Achievement unlocked- How rude")
                        if Ccbba == "2":
                            print("")
                            print("You run away, going down the mountain at lightning speed.")
                            print("You bolt down to the very bottom of the mountain, catching your breath from running so fast.")
                            print("You dont know why you ran, maybe it was a fear awoken deep within you,")
                            print("You sigh as you sit down. not wanting to know what was down that hole.")
                            print("You sigh as you look around. You see a large tree with red fruits growing from it.")
                            print("You also see a man walking towards the mountain.")
                            Ccbbab = input("What do you do?- (Walk to man=1, Walk to tree=2)-   ")
                            if Ccbbab == "1":
                                print("")
                                print("You approach the man, you look up and down at him, he seems to be dressed in the same clothes as you.")
                                print("He seems sad as he walks up the mountain, not noticing you until you walk up to him.")
                                print("*Hello* You say.")
                                print("He screams and shivs you with a wooden knife.")
                                print("Oops, you buggered that one up good.")
                            if Ccbbab == "2":
                                print("")
                                print("You ignore the sad man and walk towards the giant apple tree.")
                                print("A voice speaks to you, seemingly from the tree.")
                                print("")
                        if Ccbba == "1":
                            print("")
                            print("You look down the hole, it goes down very deep, so far that it seems to suck the light out of the air.")
                            print("You get a bit closer to get a better look,")
                            print("You feel your shoe slide on the cave floor")
                            print("Ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh you say as you fall down the hole.")
                            from os import environ

                            environ['PYGAME_HIDE_SUPPORT_PROMPT'] = '1'

                            import pygame

                            pygame.mixer.init()
                            pygame.mixer.music.load("M1.wav")
                            pygame.mixer.music.play()
                            while pygame.mixer.music.get_busy() == True:
                                continue
                            print("2(565)")

            if Cc == "4":
                print("")
                print("Filled with indecisiveness, you turn back and get eaten by the beast")
                print("You die because you couldn't go down any of the weathered paths. Robert frost can kiss my ass.")
                print("Achievement unlocked- No adventure for me.")
            if Cc == "3":
                print("")
                print("You walk to the right, preferring mystery than the obvious story laid out for you.")
                print("The forest stats to get darker and spookier")
                print("The gloom seeping in from all sides.")
                print("You start to get worried that you might have chosen wrong in the mystery.")
                print("But when you look back, the forest has grown around the path.")
                print("You look back ahead and continue walking")
                print("The forest closes up behind you as you walk, pushing you further into the forest.")
                Ccc = input("What do you do?- Continue=1, go back=2, cry=3-   ")
                if Ccc == "2":
                    print("")
                    print("You walk back through the forest, wanting to not go towards the dark and gloomy path")
                    print("The forest swallows you, and just as you are about to get crushed by the malicious trees, you hear a whisper from above, ")
                    print("\"Cowards are punished in the simulation\"")
                if Ccc == "1":
                    print("")
                    print("You continue forward. steeling your heart to face what comes next.")
                    print("The path stays to a relatively straight line, the trees become denser and denser until you cant tell if its day or night.")
                    print("The path suddenly changes from dirt to stone. a chill creeps down your back. you dont like this.")
                    print("You pull up and down in the ground is a hole, a singe metal ladder leading down.")
                    print("You look back and just as you expected, the path behind you has closed up,")
                    print("You dont know what to do. and then suddenly something pushes you.")
                    print("You fall.")
                    print("")
                    print("")
                    print("down")
                    print("")
                    print("")
                    print("")
                    print("")
                    print("down")
                    print("")
                    print("")
                    print("")
                    print("")
                    print("and you land down, thudding against a jelly like substance.")
                    print("You look around, but it is pitch black. you cant see a thing")
                    Ccca = input("What do you do?- (Fly away=1, Go forth in the darkness=2, Cry=3)-   ")
                    if Ccca == "1":
                        print("")
                        print("up up down down right left right left start select.")
                        print("You can now fly.")
                        print("You fly all the way out of the hole, soaring up and above the dark forest,")
                        print("You see the entire world beneath you, passing by.")
                        print("You can see Mt Ebbot as you fly past it, and then you notice a small little town")
                        print("You dive down towards the little place. Noticing all kinds of people milling about.")
                        print("And then as you set your foot down on the grou-")
                        print("Admin has swung the ban hammer. Reason- Flying is not allowed on this server.")
                        print("For an appeal Visit thisworldthesedays.com/ban-appeal-for-pyventure.html")
                    if Ccca == "2":
                        print("")
                        print("You forge ahead into the darkness, not afraid of what might be lurking in the shadows.")
                        print("Gradually the soft carpet like floor turns to a hard stone floor.")
                        print("You turn around a corner, and the room suddenly gets a little brighter.")
                        print("You see a light at the end of the room. It is floating and a bright blue colour.")
                        print("It seems to beckon you closer")
                        Cccab = input("What do you do?- walk towards-1, away-2, ")








    Yeet = input("Press any key to start again, or x to quit-   ")
else:
    print("1(989)")